export const products: Product[] = [
  {
    id: "1",
    name: "Smart Doorbell",
    description: "HD video and two-way audio for enhanced home security.",
    details: "Monitor your front door with this Smart Doorbell, which features HD video and two-way audio for clear communication with visitors. The doorbell integrates with your smartphone, allowing you to see and speak to anyone at your door from anywhere. It includes motion detection and night vision for added security, and you can set up alerts to notify you of any activity. The sleek design and easy installation make it a valuable addition to your home security system.",
    price: 29990,
    category: "smart devices",
    image: "/doorbell.jpg",
  },
  {
    id: "2",
    name: "Tablet Stand",
    description: "Adjustable stand for tablets of all sizes.",
    details: "This Adjustable Tablet Stand is perfect for hands-free use of your tablet. It supports tablets of all sizes and can be adjusted to multiple angles to find the most comfortable viewing position. Made from durable materials, it provides a stable and secure base for your device. The stand's compact design makes it easy to carry, and its foldable feature allows for convenient storage. Ideal for video calls, watching videos, or reading, it enhances your tablet experience.",
    price: 19990,
    category: "laptop accessories",
    image: "/tablet.jpg",
  },
  {
    id: "3",
    name: "Wireless Keyboard",
    description: "Compact keyboard with long battery life.",
    details: "Upgrade your typing experience with this Compact Wireless Keyboard. It features a sleek, minimalistic design that fits perfectly into any workspace. The keyboard offers quiet and responsive keys, ensuring a comfortable typing experience. Its wireless connectivity eliminates cable clutter, and the long battery life means you won't need to replace batteries frequently. With easy-to-use shortcut keys and a slim profile, this keyboard is both functional and stylish.",
    price: 9000,
    category: "laptop accessories",
    image: "/product-8.jpg",
  },
  {
    id: "4",
    name: "Smart Light Bulb",
    description: "Control the brightness and color of your lights.",
    details: "Transform your living space with this Smart Light Bulb, which allows you to control both the brightness and color of your lights. Compatible with major smart home systems, it can be controlled via a smartphone app or voice commands. Customize the lighting to fit any mood or occasion, from bright daylight to warm, cozy tones. The bulb is energy-efficient, helping you save on electricity bills while providing long-lasting performance.",
    price: 49250,
    category: "smart devices",
    image: "/bulb.jpg",
  },
  {
    id: "5",
    name: "Streaming Media Player",
    description: "Stream your favorite shows in 4K UHD.",
    details: "Enhance your home entertainment with this Streaming Media Player, which delivers 4K UHD streaming for the best picture quality. It supports a wide range of streaming services and apps, giving you access to your favorite shows, movies, and music. The media player features a user-friendly interface and includes a remote control for easy navigation. With built-in Wi-Fi and Ethernet support, you can enjoy seamless streaming without interruptions.",
    price: 39990,
    category: "laptop accessories",
    image: "/mp3.jpg",
  },
  {
    id: "6",
    name: "Fitness Tracker",
    description: "Track your fitness goals with this smart band.",
    details: "Stay on top of your fitness goals with this advanced Fitness Tracker. It monitors your heart rate, steps, sleep patterns, and calories burned, providing comprehensive insights into your health and fitness. The tracker features a sleek design and a clear display that shows real-time data. It also supports notifications for calls, messages, and apps, keeping you connected while on the move. With a battery life of up to 10 days, it ensures you stay motivated and informed about your progress.",
    price: 18900,
    category: "smart devices",
    image: "/fitness.jpg",
  },
  {
    id: "7",
    name: "Wireless Charger",
    description: "Fast charging for all Qi-enabled devices.",
    details: "Keep your devices powered up with this Fast Wireless Charger. Compatible with all Qi-enabled devices, it provides a quick and efficient charging solution without the hassle of cables. The slim and sleek design fits seamlessly into any space, whether on your desk or nightstand. It also features an LED indicator to show the charging status and has built-in safety features to protect against overheating and overcharging.",
    price: 17000,
    category: "laptop accessories",
    image: "/product-6.jpg",
  },
  {
    id: "8",
    name: "Smart Home Hub",
    description: "Control your smart devices with voice commands.",
    details: "Transform your home into a smart home with this Smart Home Hub. It allows you to control all your smart devices from one central location using voice commands or the mobile app. The hub is compatible with a wide range of devices, including lights, thermostats, and security cameras. It also supports automation, so you can set up routines that make your home more convenient and energy-efficient. The sleek design blends into any home decor.",
    price: 39679,
    category: "smart devices",
    image: "/smarthome.jpg",
  },
  {
    id: "9",
    name: "Noise-Canceling Headphones",
    description: "Immersive sound experience with active noise cancellation.",
    details: "Immerse yourself in your music with these Noise-Canceling Headphones. Featuring active noise cancellation, they block out ambient noise so you can focus on what matters most. The headphones deliver rich, high-fidelity sound and are equipped with plush ear cushions for all-day comfort. The foldable design makes them easy to carry around, and with a battery life of up to 20 hours, you can enjoy uninterrupted listening on the go.",
    price: 49955,
    category: "headphones",
    image: "/headphone.jpg",
  },
  {
    id: "10",
    name: "4K Action Camera",
    description: "Capture every moment in stunning 4K resolution.",
    details: "Capture every moment in stunning detail with this 4K Action Camera. Perfect for adventurers and content creators, it records ultra-high-definition video and takes crisp photos even in challenging conditions. The camera is waterproof and shockproof, making it ideal for extreme sports. It also features a wide-angle lens, image stabilization, and Wi-Fi connectivity for easy sharing of your footage. The compact design ensures it won’t weigh you down, whether you're hiking, biking, or diving.",
    price: 69965,
    category: "laptop accessories",
    image: "/camera.jpg",
  },
  {
    id: "11",
    name: "Smart Thermostat",
    description: "Automate your home's temperature for energy savings.",
    details: "Automate your home's climate control with this Smart Thermostat. It learns your schedule and preferences to create the perfect temperature at all times, helping you save on energy bills. The thermostat can be controlled remotely via a smartphone app, allowing you to adjust the temperature from anywhere. It’s also compatible with voice assistants, so you can change settings with simple voice commands. The modern design fits seamlessly into any home decor.",
    price: 28921,
    category: "smart devices",
    image: "/thermo.jpg",
  },
  {
    id: "12",
    name: "Portable Power Bank",
    description: "High-capacity power bank for charging on the go.",
    details: "Never run out of battery on the go with this high-capacity Portable Power Bank. It can charge multiple devices at once, thanks to its dual USB ports, and provides enough power to recharge your smartphone several times over. The power bank is compact and lightweight, making it easy to carry in your bag or pocket. It also features an LED indicator to show the remaining battery life, so you're never caught off guard.",
    price: 15000,
    category: "laptop accessories",
    image: "/product-7.jpg",
  },
  {
    id: "13",
    name: "Bluetooth Earbuds",
    description: "Compact and comfortable wireless earbuds.",
    details: "Enjoy wireless freedom with these compact Bluetooth Earbuds. Designed for a secure and comfortable fit, they are perfect for daily use, whether you're commuting, working out, or just relaxing at home. The earbuds offer high-quality sound and a built-in microphone for clear calls. They come with a portable charging case that provides multiple recharges, ensuring you have power throughout the day.",
    price: 19990,
    category: "headphones",
    image: "/earbud.jpg",
  },
  {
    id: "14",
    name: "VR Headset",
    description: "Immerse yourself in virtual reality experiences.",
    details: "Step into another world with this immersive VR Headset. It offers a wide field of view and high-resolution display for a truly engaging virtual reality experience. The headset is lightweight and comfortable, with adjustable straps to ensure a perfect fit. It supports a wide range of VR games and applications, and the built-in headphones deliver 3D audio for a fully immersive experience. With its easy setup and compatibility with various devices, it's the perfect addition to any gaming or entertainment setup.",
    price: 59990,
    category: "laptop accessories",
    image: "/vr.jpg",
  },
  {
    id: "15",
    name: "Laptop Stand",
    description: "Adjustable stand for laptops of all sizes.",
    details: "This Adjustable Laptop Stand provides the perfect ergonomic setup for your workspace. It supports laptops of all sizes and can be adjusted to various angles to reduce neck and back strain. Made from high-quality aluminum, it is both sturdy and lightweight, with a foldable design for easy storage and portability. The stand also features a ventilated design that helps prevent your laptop from overheating during extended use.",
    price: 1759,
    category: "laptop accessories",
    image: "/laptopstand.jpg",
  },
  {
    id: "16",
    name: "Gaming Mouse",
    description: "Ergonomic design with customizable buttons.",
    details: "Enhance your gaming experience with this ergonomic Gaming Mouse. Designed for comfort during long gaming sessions, it features customizable buttons and RGB lighting to match your setup. The high-precision sensor ensures accurate tracking, while the adjustable DPI settings allow you to tailor the mouse sensitivity to your preference. Its durable build can withstand the rigors of competitive gaming, and the braided cable ensures minimal drag for smooth movement.",
    price: 6000,
    category: "laptop accessories",
    image: "/product-5.jpg",
  },
  {
    id: "17",
    name: "Bluetooth Speaker",
    description: "Portable speaker with deep bass and clear sound.",
    details: "Bring your music to life with this portable Bluetooth Speaker. Featuring deep bass and clear sound, it's perfect for any setting, whether you're at a party, a picnic, or just relaxing at home. The speaker is compact and lightweight, making it easy to carry around. It connects wirelessly to your devices and has a battery life of up to 10 hours, so you can enjoy your favorite tunes all day long. It also includes a built-in microphone for hands-free calls and a water-resistant design, making it ideal for outdoor use.",
    price: 24000,
    category: "headphones",
    image: "/product-9.jpg",
  },
  {
    id: "18",
    name: "Phone Case - Midnight Blue",
    description: "Stylish and protective phone case.",
    details: "Protect your phone in style with this Midnight Blue Phone Case. Made from durable materials, it offers excellent protection against drops, scratches, and daily wear and tear. The slim profile ensures that your phone remains sleek and easy to handle, while the precise cutouts provide easy access to all ports and buttons. The soft inner lining prevents any scratches on your device, and the textured exterior improves grip, reducing the chances of accidental drops.",
    price: 5000,
    category: "phone cases",
    image: "/product-4.jpg",
  },
  {
    id: "19",
    name: "Smartwatch Pro",
    description: "Stay connected with fitness tracking and notifications.",
    details: "The Smartwatch Pro is your ultimate fitness companion, offering a wide range of features designed to help you stay connected and active. With its sleek design and customizable watch faces, it complements any outfit, whether you're at the gym or in the office. The watch tracks your heart rate, steps, sleep, and even monitors your stress levels. It also supports notifications for calls, messages, and apps, ensuring you never miss an important update. The battery life lasts up to 7 days on a single charge, and it's water-resistant, making it perfect for swimmers.",
    price: 20000,
    category: "smart devices",
    image: "/product-1.jpg",
  },
  {
    id: "20",
    name: "Sleek Wireless Earbuds",
    description: "High-quality sound with noise cancellation.",
    details: "Experience top-tier audio quality with these Sleek Wireless Earbuds. Designed for the audiophile, they deliver crystal-clear sound with deep bass and crisp highs, all while providing active noise cancellation to block out distractions. These earbuds are lightweight and ergonomically designed for a comfortable fit, ensuring they stay in place even during intense workouts. With a long-lasting battery, you can enjoy up to 8 hours of continuous playback, and the portable charging case extends this to 24 hours. They also feature touch controls, allowing you to easily manage your music and calls without reaching for your device.",
    price: 29999,
    category: "headphones",
    image: "/product-2.jpg",
  },
];
